services:
  tor:
    image: dperson/torproxy
    container_name: tor
    restart: unless-stopped
    # expose:
    #   - "9050"  # SOCKS5 proxy
    #   - "9051"  # Control port
    ports:
      - "9050:9050"  # SOCKS5 proxy
      - "9051:9051"  # Control port
    command: -p "ergqewrgqerwgqwergwerg3er"
    environment:
      - TZ=Europe/Brussels

    networks:
      - tornet

   

  puppeteer_tor:
    build: ./puppeteer_tor
    container_name: puppeteer_tor
    volumes:
      - ./puppeteer_tor:/app
      # - tor-data:/var/lib/tor
      - /tmp/.X11-unix:/tmp/.X11-unix
    # networks:
    #   - tornet
    env_file:
      - .env
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host  # necessary to use host X11 socket
    privileged: true    # needed for Chromium sandboxing
   

networks:
  tornet:
    driver: bridge

