services:
  i2p_router:
    image: ksey/i2pd
    container_name: i2p_router
    restart: unless-stopped
    ports:
      - "4444:4444"           # HTTP Proxy
      - "7654:7654"           # Web UI
      - "12345:12345/udp"     # SSU2 / UDP Transport
      - "3456:3456"           # NTCP2 / TCP Transport
    volumes:
      - ./subscriptions.txt:/etc/i2pd/subscriptions.txt
      - i2p_data:/var/lib/i2pd
    command: [
      "--host", "0.0.0.0",
      "--sam.enabled", "true",
      "--httpproxy.enabled", "true",
      "--httpproxy.address", "0.0.0.0",
      "--httpproxy.port", "4444",
      "--addressbook.subscriptions", "/etc/i2pd/subscriptions.txt"
    ]

  puppeteer_client:
    build: ./puppeteer_i2p
    depends_on:
      - i2p_router
    env_file:
      - ./puppeteer_i2p/.env

volumes:
  i2p_data:
